---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config:
      file: my_rubocop.yml
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- spec/
- pkg/
